console.log("************************************");
console.log("              Report Card           ");
console.log("************************************");
console.log("Student Name : Sagar Vishwakarma");
console.log("Roll No. : 54");
console.log("Class : 10th");
console.log("School Name : St. George High School");
console.log("************************************");
console.log("Subjects             Grades");
console.log("************************************");
console.log("Mathematics            A");
console.log("Science                B+");
console.log("History                B");
console.log("************************************");
console.log("          End of Report Card        ");
console.log("************************************");